/* Eine einzige GROQ-Abfrage holt alles, was die Seite braucht — ein Request pro Aufruf. */

export const CONTENT_QUERY = `{
  "settings": *[_id == "siteSettings"][0]{
    brandInitial,
    brandName,
    mainNav[]{_key, label, href},
    headerSecondaryLink{label, href},
    headerCta{label, href},
    footerAbout,
    footerColumns[]{_key, title, links[]{_key, label, href}},
    footerCopyright,
    footerNote,
    seoTitle,
    seoDescription,
    shareTitle,
    shareDescription
  },
  "home": *[_id == "homePage"][0]{
    heroBadge,
    heroHeading,
    heroLead,
    heroPrimaryCta{label, href},
    heroSecondaryCta{label, href},
    showcaseTitle,
    showcaseStatus,
    showcaseSnippet{language, code, caret},
    metricsLabel,
    metrics[]{_key, label, value, fill},
    metricsFootnote,
    logosLabel,
    logos[]{_key, name, style},
    servicesEyebrow,
    servicesHeading,
    servicesLead,
    services[]{_key, title, text, tags},
    stackEyebrow,
    stackHeading,
    stackMeta,
    stackTabs[]{_key, title, summary, fileName, fileMeta, tags, snippet{language, code, caret}},
    workEyebrow,
    workHeading,
    workLink{label, href},
    featuredProjects[]->{_id, client, description, kpi, year, href},
    processEyebrow,
    processHeading,
    processSteps[]{_key, label, title, text, highlighted},
    quote,
    quoteAccent,
    quoteInitials,
    quoteAuthor,
    quoteRole,
    kpis[]{_key, value, label},
    ctaEyebrow,
    ctaHeading,
    ctaLead,
    ctaPrimary{label, href},
    ctaSecondary{label, href}
  }
}`
